apply plugin: 'com.android.library'

version = '0.0.1-SNAPSHOT'
group = 'com.netease.hearttouch'

android {
    namespace = 'com.wolfcstech.brotlij'
    ndkVersion = libs.versions.ndkVersion.get()
    compileSdk =  libs.versions.compileSdk.get().toInteger()

    android.experimentalProperties["android.ndk.suppressMinSdkVersionError"] = 21

    defaultConfig {
        minSdk = libs.versions.minSdk.get().toInteger()
        testInstrumentationRunner = "android.support.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(libs.versions.javaVersion.get())
        targetCompatibility = JavaVersion.toVersion(libs.versions.javaVersion.get())
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles.add(file("proguard-rules.pro"))
        }
    }

    externalNativeBuild {
        ndkBuild {
            path "src/main/jni/Android.mk"
        }
    }

}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testImplementation libs.junit
}
